### ISSUE TITLE
Should we add "Structured data"?

### ISSUE THREAD

**Issue by mfranzke** [schlomo/chromebooks-in-deutschland#3]
Implement structured data (JSONld, microdata or RDFa) to e.g. the products listing.
This topic probably should further get evaluated on whether it makes sense for this website at all that doesn't have any detail pages for each item.

**Comment by schlomo** [comment]
Indeed, I would argue to **not** add structured data for foreign content. I also have the impression that the Google bot doesn't actually see the generated table content (which is probably bad for SEO)
